swagger: '2.0'
info:
  title: ArgentBank API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions/{startDate}/{endDate}:
    get:
      security:
        - Bearer: []
      tags:
        - "User Transactions"
      summary: "User transactions"
      description: "Show all transactions per current month"
      operationId: "showMonthlyTransactions"
      produces:
        - "application/json"
      parameters:
        - name: "startDate"
          in: "path"
          required: true
          type: "string"
        - name: "endDate"
          in: "path"
          required: true
          type: "string"
        - in: "header"
          type: "string"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
      responses:
        '200':
          description: "User transactions retrieved successully"
          schema:
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: "Invalid Fields"
        '500':
          description: "Internal Server Error"
  /transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Transaction detail
      summary: "User transaction"
      description: "Show a transaction details"
      operationId: "showTransactionDetails"
      produces:
        - "application/json"
      parameters:
        - name: "transactionId"
          in: "path"
          description: "ID of transaction is required"
          required: true
          type: "integer"
          format: "int64"
        - in: header
          type: "string"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
      responses:
        '200':
          description: "User transaction retrieved successully"
          schema:
              $ref: '#/definitions/Transaction'
        '400':
          description: "Invalid Fields"
        '500':
          description: "Internal Server Error"
    delete:
      security:
        - Bearer: []
      tags:
        - Delete User Transaction detail
      summary: "Delete User transaction"
      description: "Show a transaction details"
      produces:
        - "application/json"
      parameters:
        - name: "transactionId"
          in: "path"
          description: "ID of transaction is required"
          required: true
          type: "integer"
          format: "int64"
        - in: header
          type: "string"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
      responses:
        '200':
          description: "User transaction deleted successully"
          schema:
              $ref: '#/definitions/DeleteTransaction'
        '400':
          description: "Invalid Fields"
        '500':
          description: "Internal Server Error"
    put:
      security:
        - Bearer: []
      tags:
        - User Transactions update
      summary: "User transactions update category and notes"
      description: "Update transaction details"
      operationId: "updateTansactionDetails"
      produces:
        - application/json
      parameters:
        - name: "transactionId"
          in: "path"
          description: "ID of transaction is required"
          required: true
          type: "integer"
          format: "int64"
        - in: "header"
          type: "string"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
        - in: "body"
          name: "body"
          description: "Update transaction attributes"
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      responses:
        '200':
          description: "User transaction updated successully"
          schema:
              $ref: '#/definitions/TransactionUpdateResponse'
        '400':
          description: "Invalid Fields"
        '500':
          description: "Internal Server Error"
securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  Transaction:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      date:
        type: "string"
        description: "transaction date"
      description:
        type: "string"
        description: "transaction description"
      amount:
        type: "number"
        description: "transaction amount"
      balance:
        type: "number"
        description: "account balance"
      type:
        type: "string"
        description: "transaction type"
      category:
        type: "string"
        description: "transaction category"
      notes:
        type: "string"
        description: "notes field for user"
  startDate:
    type: "object"
    properties:
      startDate:
        type: "string"
  endDate:
    type: "object"
    properties:
      endDate:
        type: "string"
  DeleteTransaction:
    type: "object"
    properties:
      id:
        type: "integer"
        format: int64
  TransactionUpdate:
    type: "object"
    properties:
      id:
        type: "integer"
        format: int64
      category:
        type: "string"
        description: "transaction category"
      notes:
        type: "string"
        description: "notes field for user"
  TransactionUpdateResponse:
    type: "object"
    properties:
      id:
        type: "integer"
        format: int64
      status:
        type: "integer"
      message:
        type: "string"
        description: "transaction update message"